/*
 * This Java source file was generated by the Gradle 'init' task.
 */

import data.Node;
import structure.BinaryTree;

public class App {

    public static void main(String[] args) throws Exception {
        System.out.println("test");

        BinaryTree<Integer> binaryTree = new BinaryTree<>();
        BinaryTree<Integer> binaryTree2 = new BinaryTree<>();
//        Queue<Node> queue = new Queue<>();


        // adds nodes to the tree
//        binaryTree.setRoot(new Node<>(1));
//        binaryTree.getRoot().setLeft(new Node<>(2));
//        binaryTree.getRoot().setRight(new Node<>(3));

        //left
//        binaryTree.getRoot().getLeft().setLeft(new Node<>(4));


        //right
//        binaryTree.getRoot().getRight().setLeft(new Node<>(15));
//        binaryTree.getRoot().getRight().setRight(new Node<>(33));

        System.out.println(binaryTree.getSumOfOddNumber());
//        binaryTree.getRoot().getRight().getRight().setRight(new Node(10));
//        binaryTree.getRoot().getLeft().getLeft().setLeft(new Node(5));
//        binaryTree.getRoot().getLeft().getLeft().setRight(new Node(10));


//        System.out.println(binaryTree2.breadthFirst(binaryTree));

//        System.out.println("inorder");
//        System.out.println("Before");
//        binaryTree.inOrderTraverse(binaryTree.getRoot());
//        System.out.println();
//        System.out.println("After");
//        BinaryTree<String> newTree =binaryTree.fizzBzzTree(binaryTree);
//        newTree.inOrderTraverse(newTree.getRoot());
//        System.out.println(binaryTree.getMax());
//        System.out.println("");
//        System.out.println("-------------------");
//        System.out.println("");
//        System.out.println("inorder");
//        binaryTree.inOrderTraverse(binaryTree.getRoot());
//        System.out.println("");
//        System.out.println("-------------------");
//        System.out.println();
//        System.out.println("postorder");
//        binaryTree.postOrderTraverse(binaryTree.getRoot());
//        System.out.println("");
//        System.out.println("-------------------");
//        System.out.println();
//        System.out.println("preorder");
//        binaryTree.preOrderTraverse(binaryTree.getRoot());
//        System.out.println("");
//
//        System.out.println("-------------------");
//
//        BinarySearchTree binarySearchTree = new BinarySearchTree();
////        System.out.println(binarySearchTree.isEmpty());
//        binarySearchTree.add(5);
//        binarySearchTree.add(7);
//        binarySearchTree.add(3);
//        binarySearchTree.add(10);
//        binarySearchTree.add(2);
//        binarySearchTree.add(4);
//        binarySearchTree.add(-1);
//        System.out.println(binarySearchTree.breadthFirst(binarySearchTree));
//        System.out.println(binarySearchTree.getRoot());

    }
}
