/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package sort;

import java.util.Arrays;

public class App {

    public static void main(String[] args) {
        Sort sort = new Sort();

        int[] testArray= {1,2,3,45,15,6,23};

        System.out.println(Arrays.toString(sort.insertionSort(testArray)));

    }
}
