/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package linked.list;

import org.junit.Test;
import static org.junit.Assert.*;

public class AppTest {
//    @Test public void appHasAGreeting() {
//        app classUnderTest = new app();
//        assertNotNull("app should have a greeting", classUnderTest.getGreeting());
//    }
}
