/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package LinkedList;

import java.util.LinkedList;

public class App {

    public static void main(String[] args) {

//        System.out.println("hello ");
        linkedList<Integer> link = new linkedList<>();
//        linkedList<Integer> ll = new linkedList<>();


//        link.insertAtEnd(10);
//        link.insertAtEnd(11);
//        link.insertAtEnd(12);
//        link.insertAtEnd(13);
//        link.insertAtEnd(10);

        link.insertAtEnd("m");
        link.insertAtEnd("o");
        link.insertAtEnd("o");
        link.insertAtEnd("m");


        System.out.println(link);

        System.out.println("reverse Array " +link.reverse(link));

        System.out.println("is the array palindrome => " +link.palindrome(link));

        System.out.println(link);

//        System.out.println(link.includes(20));


    }
}
