/*
 * This Java source file was generated by the Gradle 'init' task.
 */

import Type.Queue;
import Type.Stack;

public class App {

    public static void main(String[] args) {
        Stack<Integer> stack= new Stack<>();
//        stack.push(1);
//        stack.push(2);
//        stack.push(3);
//        stack.push(4);
//        System.out.println(stack);
//        System.out.println(stack.pop());
//        System.out.println(stack.isEmpty());
//        System.out.println(stack.peek());
//        System.out.println(stack);


        Queue<Integer> queue= new Queue<>();
        queue.enqueue(1);
        queue.enqueue(2);
        queue.enqueue(3);
        queue.enqueue(4);
        System.out.println(queue);
        queue.dequeue();
        queue.dequeue();
        queue.dequeue();
        queue.dequeue();
        System.out.println(queue);
        queue.enqueue(4);
        queue.enqueue(3);
        queue.enqueue(2);
        System.out.println(queue);

        System.out.println(queue.isEmpty());
//        queue.enqueue(1);
//        queue.enqueue(2);
//        queue.enqueue(3);
//        queue.enqueue(4);
//        queue.enqueue(5);
//        System.out.println(queue);

//        System.out.println(queue.dequeue());
//        System.out.println(queue.dequeue());
//        System.out.println(queue.dequeue());
//        System.out.println("peek"+queue.peek());

//        System.out.println(queue);




    }
}
